# Generated by Django 5.0.8 on 2024-08-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlueVisionWeb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='SendMessage',
        ),
    ]
