# Generated by Django 5.0.8 on 2024-08-21 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlueVisionWeb_app', '0002_rename_contact_sendmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
